# Generated by Django 3.2.9 on 2021-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_promocode_usedtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='usedTimes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
