# Generated by Django 3.2.9 on 2021-11-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_promocode_usedtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
    ]
